"""
alert_gen.py -- Day 11, Layer 5: the alert generator.

--------------------------------------------------------------------------
SCOPE CHANGE FROM THE ORIGINAL DAY 11 PLAN -- read this before using this
file, since it changes what "verified" means here.

1. NO NLI ENTAILMENT CHECKER. The original plan called for running every
   generated sentence through an off-the-shelf NLI model, flagging
   anything below ~0.8 entailment against a retrieved document, then
   hand-verifying 20 alerts to tune that threshold. Descoped for time.
   No sentence-level automated verification of the generated PROSE exists
   in this file.

2. THE MITIGATION FOR THAT GAP IS STRUCTURAL, NOT A REPLACEMENT CHECK.
   Every fact that appears in an alert -- which companies, what tier,
   what evidence, what's stale, what's missing -- is computed by plain
   Python from already-scored, already-trusted fields (coverage,
   gap_flags, evidence_log), BEFORE the LLM is ever called. The LLM's
   ONLY job is turning an already-complete, already-correct set of facts
   into readable prose -- it is never asked to recall, infer, or
   reconstruct anything. This is a deliberately narrower job for the
   model than free-form summarization, and it's the direct fix for a
   real, confirmed problem found in System C's own final_report field:
   several real traces showed the agent's free-text summary contradicting
   its own evidence_log (e.g. claiming "no companies identified" on an
   event where 8 evidence-gathering calls had just succeeded). That
   happened because the summary was generated by asking the model to
   recall what it did. This file never does that -- every fact is
   pre-computed and handed to the model as fixed input, not retrieved
   from memory.

   This narrows the failure surface a lot (a model asked to describe
   given facts in prose is a much easier, much more reliable task than a
   model asked to recall its own history) but it does not make the prose
   provably correct. Manual spot-checking of generated alerts before
   trusting them for anything beyond a dissertation writeup is still
   worth doing if time allows -- just not built into this file as an
   automated step.

3. HISTORICAL PRECEDENT IS DELIBERATELY THIN, NOT FABRICATED. This
   project has no repository of past disruptions to compare a new event
   against outside its own 30-event ground truth -- and using that
   ground truth at "alert generation time" would be circular for any of
   the 30 events themselves. build_historical_precedent() says so
   directly in its output rather than inventing a comparison. See that
   function's own docstring.

4. SEVERITY IS THREE SEPARATE, LABELED SIGNALS, NEVER ONE BLENDED SCORE.
   There is no calibrated model anywhere in this project for combining
   proximity, evidence strength, and staleness into a single number --
   inventing a weighting scheme to produce one would be exactly the kind
   of fabrication the original plan's own uncertainty-section note
   warns against ("an alert stating 'concentration unknown, not
   disclosed' is more defensible than a fabricated number"). The same
   principle applies here: three real, separately-computed signals,
   never averaged into a single invented severity score.

WHAT THIS FILE READS: only `coverage`, `gap_flags`, and `evidence_log`
from a System C trace dict (the same three fields
evaluate_system_c.py's own scoring already trusts) -- never
`final_report`, for the reason above.

WHAT THIS FILE NEEDS TO WORK: nothing beyond what a trace already
contains. No changes to agent_state.py or agent_graph.py were needed --
if you want alerts to cite the exact filing (doc_id/url/published_date)
behind a piece of evidence rather than just which TOOL produced it, that
would need coverage rows to carry that detail, which they currently
don't -- noted as a real, deliberately not-taken option, not an oversight.
--------------------------------------------------------------------------
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

SIGNIFICANT_TIER_MAX = 2          # matches stopping_condition.py
RECENT_ENOUGH_DAYS = 730          # matches stopping_condition.py
EVIDENCE_TOOLS = {"get_supplier_info", "search_corpus"}  # matches system_c.py


# --------------------------------------------------------------------------- #
# Section 1: event summary -- not derived from the trace at all. These are
# the same inputs run_event.run_one_event() already takes to run the
# investigation in the first place; the alert just needs them passed
# through, not re-derived.
# --------------------------------------------------------------------------- #

@dataclass
class EventSummary:
    event_id: str
    company_name: str
    event_date: str
    hop_count: int
    max_hops: int
    stop_reason: Optional[str]


def build_event_summary(
    event_id: str, company_name: str, event_date: str, trace: dict
) -> EventSummary:
    return EventSummary(
        event_id=event_id,
        company_name=company_name,
        event_date=event_date,
        hop_count=trace.get("hop_count", 0),
        max_hops=trace.get("max_hops", 0),
        stop_reason=trace.get("stop_reason"),
    )


# --------------------------------------------------------------------------- #
# Section 2: affected suppliers -- the evidenced subset of coverage, same
# bar evaluate_system_c.py's own scoring already uses (system_c.py's
# extract_system_c_predictions): a company only counts once it has at
# least one EVIDENCE_TOOLS hit, not merely a traversal mention. Sorted by
# tier then name for a stable, predictable ordering.
# --------------------------------------------------------------------------- #

@dataclass
class AffectedSupplier:
    name: str
    tier: Optional[int]
    evidence_sources: list        # e.g. ['get_supplier_info', 'search_corpus']
    n_sources: int
    best_staleness_days: Optional[int]
    tag_mismatch: Optional[bool]


def build_affected_suppliers(coverage: dict) -> list[AffectedSupplier]:
    suppliers = []
    for row in coverage.values():
        sources = row.get("evidence_sources", []) or []
        real_sources = [s for s in sources if s in EVIDENCE_TOOLS]
        if not real_sources:
            continue  # identified structurally only -- not an "affected supplier" claim, same bar as scoring
        suppliers.append(AffectedSupplier(
            name=row["name"],
            tier=row.get("tier"),
            evidence_sources=real_sources,
            n_sources=len(real_sources),
            best_staleness_days=row.get("best_staleness_days"),
            tag_mismatch=row.get("tag_mismatch"),
        ))
    suppliers.sort(key=lambda s: (s.tier if s.tier is not None else 99, s.name))
    return suppliers


# --------------------------------------------------------------------------- #
# Section 3: severity -- three separate, labeled signals per affected
# supplier. See module docstring point 4 for why this is never blended
# into one number.
# --------------------------------------------------------------------------- #

@dataclass
class SeverityBreakdown:
    name: str
    proximity: str        # "direct (tier 1)" | "indirect (tier 2)" | "tier N (beyond significant threshold)" | "unknown"
    evidence_strength: str  # "corroborated (2+ independent sources)" | "single-sourced"
    freshness: str         # "recent (<=730 days)" | f"stale ({n} days)" | "unknown"


def _proximity_label(tier: Optional[int]) -> str:
    if tier is None:
        return "unknown"
    if tier == 1:
        return "direct (tier 1)"
    if tier == 2:
        return "indirect (tier 2)"
    return f"tier {tier} (beyond the tier-{SIGNIFICANT_TIER_MAX} significance threshold)"


def _evidence_strength_label(n_sources: int) -> str:
    return "corroborated (2+ independent sources)" if n_sources >= 2 else "single-sourced"


def _freshness_label(staleness_days: Optional[int]) -> str:
    if staleness_days is None:
        return "unknown (no dated filing evidence)"
    if staleness_days <= RECENT_ENOUGH_DAYS:
        return f"recent ({staleness_days} days old)"
    return f"stale ({staleness_days} days old, exceeds the {RECENT_ENOUGH_DAYS}-day threshold)"


def build_severity_breakdown(suppliers: list[AffectedSupplier]) -> list[SeverityBreakdown]:
    return [
        SeverityBreakdown(
            name=s.name,
            proximity=_proximity_label(s.tier),
            evidence_strength=_evidence_strength_label(s.n_sources),
            freshness=_freshness_label(s.best_staleness_days),
        )
        for s in suppliers
    ]


# --------------------------------------------------------------------------- #
# Section 4: historical precedent -- deliberately thin. See module
# docstring point 3. This function's only real job is to state the
# limitation honestly rather than have the LLM improvise one.
# --------------------------------------------------------------------------- #

def build_historical_precedent_note() -> str:
    """Fixed, honest text -- not templated per-event, since there is no
    real per-event historical comparison available to vary it with.
    Handed to the LLM as a fact to state plainly, not a prompt to
    elaborate on."""
    return (
        "No historical precedent database exists for this system. This "
        "section intentionally does not compare this event to past "
        "disruptions, since no verified repository of prior events is "
        "available outside this project's own evaluation set, and using "
        "that set here would be circular for any event contained in it."
    )


# --------------------------------------------------------------------------- #
# Section 5: uncertainty flags -- built from gap_flags plus the
# tag_mismatch/staleness signals already computed in section 3.
#
# TIER FILTERING FOR THE PROMPT: trace["gap_flags"] is already restricted
# to tier<=2 companies by construction -- stopping_condition.py's own
# check_stopping_condition() only ever computes gaps over
# `required_rows` (tier <= SIGNIFICANT_TIER_MAX), so nothing further is
# needed there. The one place a higher tier (or no tier at all -- a
# company found only via search_corpus, never confirmed by a traversal)
# COULD appear is the tag_mismatch flags added below, since those are
# derived from `suppliers` (every EVIDENCED company, any tier), not from
# gap_flags. Filtered here for consistency, so the LLM prompt never
# receives an uncertainty flag for a company outside the tier<=2
# significance threshold, matching the same bar the rest of the alert
# already uses.
#
# The omission is stated explicitly, not silent -- dropping real flags
# without saying so would itself be a small, undocumented loss of
# information, which is exactly what this project treats as
# unacceptable everywhere else (e.g. stopping_condition.py's own
# insistence on flagging gaps rather than omitting them). The full,
# unfiltered list is still returned separately for the record.
# --------------------------------------------------------------------------- #

def build_uncertainty_flags(
    trace: dict, suppliers: list[AffectedSupplier]
) -> tuple[list[str], list[str]]:
    """Returns (for_prompt, full). `for_prompt` is tier<=2 (or
    non-company-specific) only -- what the LLM actually sees. `full` is
    every flag, unfiltered -- kept on the packet for the record even
    though it's not hidden, only not spent LLM-prompt space on."""
    tier_by_name = {
        (row.get("name") or key).strip().lower(): row.get("tier")
        for key, row in (trace.get("coverage") or {}).items()
    }

    def _tier_of_flag(flag_text: str) -> Optional[int]:
        name = flag_text.split(":", 1)[0].strip().lower()
        return tier_by_name.get(name)

    full: list[str] = list(trace.get("gap_flags", []) or [])  # already tier<=2 by construction
    for s in suppliers:
        if s.tag_mismatch:
            full.append(f"{s.name}: evidence found, but not tagged to this specific event "
                        f"(tag_mismatch) -- treat with extra caution")
    if trace.get("stop_reason") == "hop_cap_reached":
        full.append("Investigation stopped because the turn budget was exhausted, "
                     "not because coverage was confirmed complete.")

    significant_tier = lambda t: t is None or t <= SIGNIFICANT_TIER_MAX  # noqa: E731
    for_prompt = [f for f in full if significant_tier(_tier_of_flag(f))]

    return for_prompt, full


# --------------------------------------------------------------------------- #
# Assembling the full evidence packet -- everything the LLM will see.
# Pure data, no LLM call yet -- directly inspectable/testable on its own.
# --------------------------------------------------------------------------- #

@dataclass
class AlertEvidencePacket:
    summary: EventSummary
    suppliers: list[AffectedSupplier]
    severity: list[SeverityBreakdown]
    historical_precedent: str
    uncertainty_flags: list[str]           # tier<=2 only -- what the LLM sees
    uncertainty_flags_full: list[str]      # every flag, unfiltered -- for the record
    n_uncertainty_flags_omitted: int = field(init=False)

    def __post_init__(self):
        self.n_uncertainty_flags_omitted = len(self.uncertainty_flags_full) - len(self.uncertainty_flags)


def build_evidence_packet(
    event_id: str, company_name: str, event_date: str, trace: dict
) -> AlertEvidencePacket:
    suppliers = build_affected_suppliers(trace.get("coverage", {}) or {})
    uncertainty_for_prompt, uncertainty_full = build_uncertainty_flags(trace, suppliers)
    return AlertEvidencePacket(
        summary=build_event_summary(event_id, company_name, event_date, trace),
        suppliers=suppliers,
        severity=build_severity_breakdown(suppliers),
        historical_precedent=build_historical_precedent_note(),
        uncertainty_flags=uncertainty_for_prompt,
        uncertainty_flags_full=uncertainty_full,
    )


def packet_as_markdown(packet: AlertEvidencePacket) -> str:
    """Renders exactly what the LLM prompt will contain -- tier<=2
    uncertainty flags only, with an explicit, honest note on how many
    lower-tier/unconfirmed-tier flags were left out and where to find
    them, never a silent drop."""
    s = packet.summary
    lines = [
        f"# Alert: {s.company_name} ({s.event_id})",
        f"Event date: {s.event_date} | Investigation used {s.hop_count}/{s.max_hops} turns "
        f"| stopped: {s.stop_reason}",
        "",
        "## Affected suppliers",
    ]
    if not packet.suppliers:
        lines.append("None evidenced -- see uncertainty flags below.")
    for sup in packet.suppliers:
        lines.append(f"- **{sup.name}** -- {_proximity_label(sup.tier)}, "
                     f"sources: {', '.join(sup.evidence_sources)}")

    lines += ["", "## Severity breakdown (three independent signals, not a blended score)"]
    for sev in packet.severity:
        lines.append(f"- **{sev.name}**: proximity={sev.proximity} | "
                     f"evidence={sev.evidence_strength} | freshness={sev.freshness}")

    lines += ["", "## Historical precedent", packet.historical_precedent]

    lines += ["", "## Uncertainty flags (tier <= 2 significance only)"]
    if not packet.uncertainty_flags:
        lines.append("None recorded.")
    for f in packet.uncertainty_flags:
        lines.append(f"- {f}")
    if packet.n_uncertainty_flags_omitted > 0:
        lines.append(f"- ({packet.n_uncertainty_flags_omitted} further gap(s) at tier 3+ or "
                     f"unconfirmed tier omitted here for brevity -- see the full trace's "
                     f"gap_flags / uncertainty_flags_full for the complete list)")

    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# The LLM call -- prose only, no facts introduced. Accepts any
# LangChain-compatible chat model, same convention as llm_setup.build_llm().
# --------------------------------------------------------------------------- #

ALERT_PROMPT_TEMPLATE = """You are writing a supply chain disruption alert for an analyst audience.

You are given a COMPLETE, ALREADY-VERIFIED set of facts below. Your only
job is to write them up as clear, professional prose, organized into
exactly these five sections, in this order:

1. Event Summary
2. Affected Suppliers
3. Severity (per-dimension)
4. Historical Precedent
5. Uncertainty Flags

RULES, followed strictly:
- Use ONLY the facts given below. Do not add a single company, date,
  number, or claim that is not explicitly present in this input.
- Cite the source of every claim about a specific company inline (e.g.
  "(get_supplier_info)" or "(search_corpus)"), using exactly the source
  names given below -- do not invent a more specific citation than the
  data actually supports.
- If a section's input says something is unknown, missing, or not
  available, say so plainly in the prose. Do not soften this into vague,
  confident-sounding language, and do not fill the gap with an inference.
- Do not blend the three severity signals (proximity, evidence strength,
  freshness) into a single severity score or rating -- present them
  as three separate, labeled facts per company, exactly as given.
- Write the Historical Precedent section using the note given below,
  essentially as-is -- do not invent a comparison to fill the space.

FACTS:

{evidence_packet_markdown}
"""


def render_alert_prompt(packet: AlertEvidencePacket) -> str:
    return ALERT_PROMPT_TEMPLATE.format(evidence_packet_markdown=packet_as_markdown(packet))


def generate_alert(
    event_id: str,
    company_name: str,
    event_date: str,
    trace: dict,
    llm=None,
) -> dict:
    """
    llm : any object with a LangChain-compatible .invoke(str) -> message
          interface (e.g. llm_setup.build_llm()'s return value), or None.
          If None, returns the plain markdown rendering of the evidence
          packet with no LLM call at all -- a safe, always-available
          fallback, and useful for a quick look at exactly what facts
          would be handed to the model.

    Returns {"packet": AlertEvidencePacket, "prompt": str, "alert_text": str}.
    "alert_text" is the LLM's prose if llm was given, else the same
    markdown packet_as_markdown() would produce.
    """
    packet = build_evidence_packet(event_id, company_name, event_date, trace)
    prompt = render_alert_prompt(packet)

    if llm is None:
        alert_text = packet_as_markdown(packet)
    else:
        print("using LLM...")
        response = llm.invoke(prompt)
        alert_text = getattr(response, "content", str(response))

    return {"packet": packet, "prompt": prompt, "alert_text": alert_text}


# --------------------------------------------------------------------------- #
# Batch mode -- runs every trace file in a directory, one alert each.
# Mirrors run_all_events.py's own pattern: build the expensive resource
# (the LLM) ONCE, loop over every event, save each result as it finishes,
# and if one event fails, log it and keep going rather than losing the
# whole batch.
# --------------------------------------------------------------------------- #

def _company_and_date_for_event(event_id: str, gt_dir: Optional[str]) -> tuple[str, str]:
    """Looks up the real company name and event date from the ground
    truth if gt_dir is given (same source run_all_events.py itself
    reads). Falls back to a plain event_id-derived guess and "unknown"
    date if gt_dir isn't given, so this file still runs with zero other
    project files available."""
    if gt_dir:
        try:
            from ground_truth import load_ground_truth
            gt = load_ground_truth(gt_dir)
            record = gt.get(event_id)
            if record:
                company = (record.get("directly_affected")
                           or event_id.split("_", 1)[-1].rsplit("_", 1)[0].replace("_", " "))
                date = record.get("date_news_first") or "unknown"
                return company, date
        except Exception as exc:
            print(f"    [warning] could not load ground truth for {event_id}: {exc}")

    company_guess = event_id.split("_", 1)[-1].rsplit("_", 1)[0].replace("_", " ")
    return company_guess, "unknown"


def generate_all_alerts(
    traces_dir: str,
    output_dir: str,
    llm=None,
    gt_dir: Optional[str] = None,
) -> dict:
    """Generates one alert per trace file found in traces_dir, writes
    each as a .md file in output_dir (named after the event_id), and
    returns {event_id: "ok" | "error: <message>"}. Continues past a
    single event's failure rather than aborting the whole batch, same
    reasoning as run_all_events.py's own retry/continue logic."""
    import glob
    import json
    import os

    os.makedirs(output_dir, exist_ok=True)
    trace_paths = sorted(glob.glob(os.path.join(traces_dir, "*.json")))
    if not trace_paths:
        raise FileNotFoundError(f"No trace files found in {traces_dir!r}")

    results = {}
    for i, path in enumerate(trace_paths, start=1):
        event_id = os.path.splitext(os.path.basename(path))[0]
        print(f"[{i}/{len(trace_paths)}] {event_id}")
        try:
            with open(path, encoding="utf-8") as f:
                trace = json.load(f)
            company_name, event_date = _company_and_date_for_event(event_id, gt_dir)
            result = generate_alert(event_id, company_name, event_date, trace, llm=llm)

            out_path = os.path.join(output_dir, f"{event_id}.md")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(result["alert_text"])

            results[event_id] = "ok"
        except Exception as exc:
            print(f"    ERROR -- {exc}")
            results[event_id] = f"error: {exc}"

    n_ok = sum(1 for v in results.values() if v == "ok")
    print(f"\n{n_ok} / {len(results)} alerts generated successfully. Written to {output_dir}/")
    return results


# --------------------------------------------------------------------------- #
# Standalone check -- single trace, or a full batch
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--batch", action="store_true",
                     help="Run every trace in --traces-dir instead of a single file")
    ap.add_argument("trace_or_dir", help="A single trace .json path, or (with --batch) a directory of them")
    ap.add_argument("--out-dir", default="results/alerts", help="Batch mode: where to write the .md alerts")
    ap.add_argument("--gt-dir", default=None, help="Optional: ground_truth_batch*.json directory, for real company names/dates")
    ap.add_argument("--provider", default=None, choices=["ollama", "groq"],
                     help="If given, calls llm_setup.build_llm() to write real prose. Omit to just print the raw facts (no LLM call).")
    ap.add_argument("--model", default=None, help="Optional model override, passed through to build_llm()")
    args = ap.parse_args()

    llm = None
    if args.provider:
        from llm_setup import build_llm
        llm = build_llm(provider=args.provider, model=args.model)

    if args.batch:
        generate_all_alerts(args.trace_or_dir, args.out_dir, llm=llm, gt_dir=args.gt_dir)
    else:
        import json

        with open(args.trace_or_dir, encoding="utf-8") as f:
            trace = json.load(f)
        event_id = args.trace_or_dir.rsplit("/", 1)[-1].removesuffix(".json")
        company_name, event_date = _company_and_date_for_event(event_id, args.gt_dir)
        result = generate_alert(event_id, company_name, event_date, trace, llm=llm)
        print(result["alert_text"])